Do not fail on Fastly POST /tls/private_keys
It's not an idempotent operation, the request will fail with 400 if the
key exists. It would be great if we could check if the key exists first,
before POST-ing. It would be even better if we could PATCH instead of
POST, same as we do for the certificate, but the Fastly API doesn't
support that request type.

The logs were too verbose by default, especially with all the TLS info.
Only run curl in --verbose mode when the job itself runs in debug mode,
otherwise keep it on the down low, as the UNIX philosophy recommends.

Signed-off-by: Gerhard Lazu <gerhard@lazu.co.uk>

diff --git a/k8s/changelog/tls-sync-fastly.yml b/k8s/changelog/tls-sync-fastly.yml
--- a/k8s/changelog/tls-sync-fastly.yml
+++ b/k8s/changelog/tls-sync-fastly.yml
@@ -25,10 +25,13 @@ spec:
 #! https://github.com/k14s/ytt/issues/177
 #@yaml/text-templated-strings
               - |-
-                if [ -z "$DEBUG" ]
+                if [ -n "$DEBUG" ]
                 then
+                  CURL_OPTIONS="--verbose"
+                else
                   echo "Fail job on error..."
                   set -e
+                  set -o pipefail
                 fi
 
                 #! https://developer.fastly.com/reference/api/tls/custom-certs/private-keys/
@@ -43,7 +46,10 @@ spec:
                   }
                 }
                 EOF
-                curl --verbose --silent --fail --show-error \
+                echo "But don't fail POST-ing private keys, as it's not idempotent"
+                echo "This Fastly support ticket has all the details: https://support.fastly.com/hc/en-us/requests/329710"
+                echo "TODO: What is the simplest way of checking that a private key exists?"
+                curl $CURL_OPTIONS --silent --show-error \
                   --header "Accept: application/vnd.api+json" \
                   --header "Content-Type: application/vnd.api+json" \
                   --header "Fastly-Key: $FASTLY_API_TOKEN" \
@@ -62,7 +68,7 @@ spec:
                   }
                 }
                 EOF
-                curl --verbose --silent --fail --show-error \
+                curl $CURL_OPTIONS --silent --fail --show-error \
                   --header "Accept: application/vnd.api+json" \
                   --header "Content-Type: application/vnd.api+json" \
                   --header "Fastly-Key: $FASTLY_API_TOKEN" \
