Fail job if Fastly API requests fail
A few other related improvements:

* do not fail job when running in debug mode, -d
* filter out FASTLY_API_TOKEN from logs 🙄
* add missed Prometheus scrape pod annotation

This will keep failing next time it is scheduled to run, but that's OK,
it is meant to be a reminder that it needs fixing. FWIW:
https://support.fastly.com/hc/en-us/requests/329710

Signed-off-by: Gerhard Lazu <gerhard@lazu.co.uk>

diff --git a/k8s/changelog.yml b/k8s/changelog.yml
--- a/k8s/changelog.yml
+++ b/k8s/changelog.yml
@@ -142,6 +142,8 @@ metadata:
     app: app
     keel.sh/policy: force
     keel.sh/match-tag: "true"
+    prometheus.io/scrape: "true"
+    prometheus.io/port: "4000"
 spec:
   replicas: 1
   selector:
@@ -447,6 +449,12 @@ spec:
             - -c
             args:
             - |-
+              if [ -z "$DEBUG" ]
+              then
+                echo "Fail job on error..."
+                set -e
+              fi
+
               #! https://developer.fastly.com/reference/api/tls/custom-certs/private-keys/
               cat > /tmp/key.json <<EOF
               {
@@ -459,12 +467,12 @@ spec:
                 }
               }
               EOF
-              curl --verbose --silent \
+              curl --verbose --silent --fail --show-error \
                 --header "Accept: application/vnd.api+json" \
                 --header "Content-Type: application/vnd.api+json" \
                 --header "Fastly-Key: $FASTLY_API_TOKEN" \
                 --data @/tmp/key.json \
-                https://api.fastly.com/tls/private_keys
+                https://api.fastly.com/tls/private_keys 2>&1 | grep -v "$FASTLY_API_TOKEN"
 
               #! https://developer.fastly.com/reference/api/tls/custom-certs/certificates/
               cat > /tmp/crt.json <<EOF
@@ -478,13 +486,13 @@ spec:
                 }
               }
               EOF
-              curl --verbose --silent \
+              curl --verbose --silent --fail --show-error \
                 --header "Accept: application/vnd.api+json" \
                 --header "Content-Type: application/vnd.api+json" \
                 --header "Fastly-Key: $FASTLY_API_TOKEN" \
                 --request PATCH \
                 --data @/tmp/crt.json \
-                https://api.fastly.com/tls/certificates/1LA0UjkMfnnMwzglSLdAc
+                https://api.fastly.com/tls/certificates/1LA0UjkMfnnMwzglSLdAc 2>&1 | grep -v "$FASTLY_API_TOKEN"
 
               if [ -n "$DEBUG" ]
               then
diff --git a/k8s/changelog/tls-sync-fastly.yml b/k8s/changelog/tls-sync-fastly.yml
--- a/k8s/changelog/tls-sync-fastly.yml
+++ b/k8s/changelog/tls-sync-fastly.yml
@@ -25,6 +25,12 @@ spec:
 #! https://github.com/k14s/ytt/issues/177
 #@yaml/text-templated-strings
               - |-
+                if [ -z "$DEBUG" ]
+                then
+                  echo "Fail job on error..."
+                  set -e
+                fi
+
                 #! https://developer.fastly.com/reference/api/tls/custom-certs/private-keys/
                 cat > /tmp/key.json <<EOF
                 {
@@ -37,12 +43,12 @@ spec:
                   }
                 }
                 EOF
-                curl --verbose --silent \
+                curl --verbose --silent --fail --show-error \
                   --header "Accept: application/vnd.api+json" \
                   --header "Content-Type: application/vnd.api+json" \
                   --header "Fastly-Key: $FASTLY_API_TOKEN" \
                   --data @/tmp/key.json \
-                  https://api.fastly.com/tls/private_keys
+                  https://api.fastly.com/tls/private_keys 2>&1 | grep -v "$FASTLY_API_TOKEN"
 
                 #! https://developer.fastly.com/reference/api/tls/custom-certs/certificates/
                 cat > /tmp/crt.json <<EOF
@@ -56,13 +62,13 @@ spec:
                   }
                 }
                 EOF
-                curl --verbose --silent \
+                curl --verbose --silent --fail --show-error \
                   --header "Accept: application/vnd.api+json" \
                   --header "Content-Type: application/vnd.api+json" \
                   --header "Fastly-Key: $FASTLY_API_TOKEN" \
                   --request PATCH \
                   --data @/tmp/crt.json \
-                  https://api.fastly.com/tls/certificates/(@= data.values.fastly.certificate_id @)
+                  https://api.fastly.com/tls/certificates/(@= data.values.fastly.certificate_id @) 2>&1 | grep -v "$FASTLY_API_TOKEN"
 
                 if [ -n "$DEBUG" ]
                 then
